"""
Ice Lake Configurator - Dynamic TSLMT Spec Generator

This script reads configuration from a YAML file and generates:
1. A customized ice_lake.tslmt boilerplate spec
2. An updated constraints_ice_lake.json validation file
3. Optionally updates the game C file with matching constants

Configuration parameters:
- grid_size: Size of the grid (e.g., 4 for 4x4, 8 for 8x8)
- goal: {x, y} position of the goal
- holes: List of {x, y} hole positions

Usage:
    python -m pipeline.ice_lake_configurator configs/ice_lake.yaml
    python -m pipeline.ice_lake_configurator --grid-size 6 --goal 5 5 --holes 1,1 2,2 3,3
"""

import argparse
import json
import yaml
from pathlib import Path
from typing import List, Tuple, Optional


def generate_tslmt_spec(
    grid_size: int,
    goal_x: int,
    goal_y: int,
    holes: List[Tuple[int, int]],
) -> str:
    """
    Generate a complete ice_lake.tslmt specification with the given parameters.

    Args:
        grid_size: Grid dimensions (grid_size x grid_size)
        goal_x: Goal X coordinate
        goal_y: Goal Y coordinate
        holes: List of (x, y) hole positions

    Returns:
        Complete TSLMT specification string
    """
    bound_max = grid_size - 1

    # Generate hole constants
    hole_constants = []
    for i, (hx, hy) in enumerate(holes):
        hole_constants.append(f"HOLE_{i}_X = i{hx}();")
        hole_constants.append(f"HOLE_{i}_Y = i{hy}();")

    hole_constants_str = "\n".join(hole_constants)

    # Generate atHolePos predicate (OR of all hole positions)
    if len(holes) == 1:
        at_hole_pos = f"(eq x HOLE_0_X) && (eq y HOLE_0_Y)"
    else:
        hole_checks = [f"((eq x HOLE_{i}_X) && (eq y HOLE_{i}_Y))" for i in range(len(holes))]
        at_hole_pos = " || ".join(hole_checks)

    spec = f'''var Int x
var Int y
var Bool atGoal

SPECIFICATION

/* 2D Ice Lake: Robot navigates {grid_size}x{grid_size} grid avoiding holes to reach the goal */
/* Generated by ice_lake_configurator.py */
/* Grid: {grid_size}x{grid_size} (positions 0-{bound_max}) */
/* Goal: ({goal_x},{goal_y}) */
/* Holes: {len(holes)} hole(s) at {holes} */

GOAL_X = i{goal_x}();
GOAL_Y = i{goal_y}();
BOUND_MIN = i0();
BOUND_MAX = i{bound_max}();

/* Hole positions */
{hole_constants_str}

/* Movement predicates */
stayX = [x <- x];
stayY = [y <- y];
moveRight =  [x <- add x i1()] && [y <- y];
moveLeft = [x <- sub x i1()] && [y <- y];
moveUp = [y <- add y i1()] && [x <- x];
moveDown = [y <- sub y i1()] && [x <- x];

/* Position predicates */
atGoalPos = (eq x GOAL_X) && (eq y GOAL_Y);
inBounds = (gte x BOUND_MIN) && (lte x BOUND_MAX) && (gte y BOUND_MIN) && (lte y BOUND_MAX);

/* Hole position check - true if on any hole */
atHolePos = {at_hole_pos};

/* Safe move checks - don't move into any hole */

assume {{
    inBounds;
    !atHolePos;
}}

guarantee {{
    /* Initial state */
    stayX && stayY && [atGoal <- false];

    /* Stay in bounds */
    G inBounds;

    /* Movement: exactly one direction or stay */
    X G ((stayX && stayY) ||
         (moveRight && (lt x BOUND_MAX)) ||
         (moveLeft && (gt x BOUND_MIN)) ||
         (moveUp && (lt y BOUND_MAX)) ||
         (moveDown && (gt y BOUND_MIN)));

    /* Goal flag: set when reaching goal */
    X G (atGoalPos -> [atGoal <- true]);
    X G (atGoal -> [atGoal <- true]);
    X G (!atGoalPos && !atGoal -> [atGoal <- false]);

}}

{{{{GUARANTEE_BLOCK}}}}
'''
    return spec


def generate_constraints_json(
    grid_size: int,
    goal_x: int,
    goal_y: int,
    holes: List[Tuple[int, int]],
) -> dict:
    """
    Generate constraints JSON for runtime validation.

    Args:
        grid_size: Grid dimensions
        goal_x: Goal X coordinate
        goal_y: Goal Y coordinate
        holes: List of (x, y) hole positions

    Returns:
        Dictionary for JSON serialization
    """
    bound_max = grid_size - 1

    return {
        "bounds": {
            "xmin": 0,
            "xmax": bound_max,
            "ymin": 0,
            "ymax": bound_max
        },
        "holes": [{"x": hx, "y": hy} for hx, hy in holes],
        "goal": {"x": goal_x, "y": goal_y},
        "start": {"x": 0, "y": 0},
        "max_steps": 1000,
        "description": f"Ice Lake {grid_size}x{grid_size} grid - robot must reach goal ({goal_x},{goal_y}) while avoiding {len(holes)} hole(s)"
    }


def update_game_c_defines(
    game_path: Path,
    grid_size: int,
    goal_x: int,
    goal_y: int,
    holes: List[Tuple[int, int]],
) -> str:
    """
    Generate updated game C file content with matching constants.

    Note: This generates a header-style defines block that can be used
    to compile the game with custom parameters.
    """
    defines = f"""/* Generated by ice_lake_configurator.py */
#define GRID_SIZE {grid_size}
#define GOAL_X {goal_x}
#define GOAL_Y {goal_y}
#define NUM_HOLES {len(holes)}
"""

    # Generate hole arrays initialization
    hole_x_init = ", ".join(str(hx) for hx, _ in holes)
    hole_y_init = ", ".join(str(hy) for _, hy in holes)

    return defines, hole_x_init, hole_y_init


def update_yaml_config(
    yaml_path: Path,
    grid_size: int,
    goal_x: int,
    goal_y: int,
    holes: List[Tuple[int, int]],
) -> dict:
    """
    Update the YAML config file with new ice_lake settings.
    """
    if yaml_path.exists():
        with open(yaml_path, 'r') as f:
            config = yaml.safe_load(f)
    else:
        config = {}

    # Update ice_lake section
    config['ice_lake'] = {
        'grid_size': grid_size,
        'goal': {'x': goal_x, 'y': goal_y},
        'holes': [{'x': hx, 'y': hy} for hx, hy in holes]
    }

    return config


def load_config_from_yaml(yaml_path: Path) -> Tuple[int, int, int, List[Tuple[int, int]]]:
    """
    Load ice lake configuration from a YAML file.

    Returns:
        Tuple of (grid_size, goal_x, goal_y, holes)
    """
    with open(yaml_path, 'r') as f:
        config = yaml.safe_load(f)

    ice_lake = config.get('ice_lake', {})

    grid_size = ice_lake.get('grid_size', 4)
    goal = ice_lake.get('goal', {'x': 3, 'y': 3})
    goal_x = goal.get('x', 3)
    goal_y = goal.get('y', 3)

    holes_config = ice_lake.get('holes', [{'x': 1, 'y': 1}])
    holes = [(h.get('x', 1), h.get('y', 1)) for h in holes_config]

    return grid_size, goal_x, goal_y, holes


def parse_hole_arg(hole_str: str) -> Tuple[int, int]:
    """Parse a hole argument like '1,2' into (1, 2)."""
    parts = hole_str.split(',')
    if len(parts) != 2:
        raise ValueError(f"Invalid hole format: {hole_str}. Expected 'x,y'")
    return int(parts[0]), int(parts[1])


def main():
    parser = argparse.ArgumentParser(
        description='Generate Ice Lake TSLMT spec with custom configuration',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  # Use configuration from YAML file
  python -m pipeline.ice_lake_configurator configs/ice_lake.yaml

  # Override with command-line arguments
  python -m pipeline.ice_lake_configurator configs/ice_lake.yaml --grid-size 6 --goal 5 5

  # Create 8x8 grid with multiple holes
  python -m pipeline.ice_lake_configurator configs/ice_lake.yaml --grid-size 8 --goal 7 7 --holes 1,1 2,3 4,5

  # Preview without writing files
  python -m pipeline.ice_lake_configurator configs/ice_lake.yaml --dry-run
'''
    )

    parser.add_argument(
        'config',
        type=Path,
        help='Path to the YAML configuration file'
    )
    parser.add_argument(
        '--grid-size', '-g',
        type=int,
        help='Grid size (e.g., 4 for 4x4 grid)'
    )
    parser.add_argument(
        '--goal',
        type=int,
        nargs=2,
        metavar=('X', 'Y'),
        help='Goal position (e.g., --goal 3 3)'
    )
    parser.add_argument(
        '--holes',
        type=str,
        nargs='+',
        metavar='X,Y',
        help='Hole positions (e.g., --holes 1,1 2,2 3,3)'
    )
    parser.add_argument(
        '--output-dir', '-o',
        type=Path,
        default=None,
        help='Output directory (defaults to project root)'
    )
    parser.add_argument(
        '--dry-run', '-n',
        action='store_true',
        help='Print generated spec without writing files'
    )
    parser.add_argument(
        '--update-yaml',
        action='store_true',
        help='Update the YAML config file with new settings'
    )

    args = parser.parse_args()

    # Determine project root (parent of configs directory)
    project_root = args.config.parent.parent
    if args.output_dir:
        project_root = args.output_dir

    # Load base config from YAML
    if args.config.exists():
        grid_size, goal_x, goal_y, holes = load_config_from_yaml(args.config)
    else:
        # Defaults
        grid_size, goal_x, goal_y, holes = 4, 3, 3, [(1, 1)]

    # Override with command-line arguments
    if args.grid_size:
        grid_size = args.grid_size
    if args.goal:
        goal_x, goal_y = args.goal
    if args.holes:
        holes = [parse_hole_arg(h) for h in args.holes]

    # Validate configuration
    bound_max = grid_size - 1
    if goal_x > bound_max or goal_y > bound_max:
        raise ValueError(f"Goal ({goal_x},{goal_y}) is outside grid bounds (0-{bound_max})")
    for hx, hy in holes:
        if hx > bound_max or hy > bound_max:
            raise ValueError(f"Hole ({hx},{hy}) is outside grid bounds (0-{bound_max})")
        if hx == goal_x and hy == goal_y:
            raise ValueError(f"Hole cannot be at goal position ({goal_x},{goal_y})")

    # Generate files
    tslmt_spec = generate_tslmt_spec(grid_size, goal_x, goal_y, holes)
    constraints = generate_constraints_json(grid_size, goal_x, goal_y, holes)

    print(f"Ice Lake Configuration:")
    print(f"  Grid Size: {grid_size}x{grid_size}")
    print(f"  Goal: ({goal_x}, {goal_y})")
    print(f"  Holes: {holes}")
    print()

    if args.dry_run:
        print("=== Generated TSLMT Spec ===")
        print(tslmt_spec)
        print()
        print("=== Generated Constraints JSON ===")
        print(json.dumps(constraints, indent=2))
        return

    # Write files
    boilerplate_path = project_root / 'boilerplates' / 'ice_lake.tslmt'
    constraints_path = project_root / 'constraints' / 'constraints_ice_lake.json'

    print(f"Writing boilerplate spec to: {boilerplate_path}")
    with open(boilerplate_path, 'w') as f:
        f.write(tslmt_spec)

    print(f"Writing constraints to: {constraints_path}")
    with open(constraints_path, 'w') as f:
        json.dump(constraints, f, indent=2)
        f.write('\n')

    # Optionally update YAML config
    if args.update_yaml:
        updated_config = update_yaml_config(args.config, grid_size, goal_x, goal_y, holes)
        print(f"Updating YAML config: {args.config}")
        with open(args.config, 'w') as f:
            yaml.dump(updated_config, f, default_flow_style=False, sort_keys=False)

    print()
    print("Done! Files updated successfully.")
    print()
    print("Next steps:")
    print(f"  1. Run synthesis: python run_pipeline.py ice_lake")
    print(f"  2. Test the game: ./games/ice_lake_game")


if __name__ == '__main__':
    main()
